services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=mydatabase
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
volumes:
   db_data:

